import type { Locale } from "@/lib/i18n/dict";
import { REPORT_DE } from "@/lib/i18n/locales/de";

/** Report-content dictionary (English key → Korean). Used by builders at generation time and by the renderer for chrome. */
export const REPORT_KO: Record<string, string> = {
  // titles
  "AI Evaluation Report": "AI 평가 리포트",
  "AI System Verification Report": "AI 시스템 검증 리포트(시험성적서)",
  "NIST ARIA Evaluation Report (AI 200-3 worksheets)": "NIST ARIA 평가 리포트(AI 200-3 워크시트)",
  "ISO/IEC 42001 Evidence Pack": "ISO/IEC 42001 증적 팩",
  "EU AI Act Evidence Pack": "EU AI Act 증적 팩",
  "NIST AI RMF Evidence Pack": "NIST AI RMF 증적 팩",
  "Korea AI Basic Act Evidence Pack": "AI 기본법 증적 팩",
  "AI Passport (living factsheet)": "AI Passport(라이브 팩트시트)",
  // disclaimers
  "This run was executed in DEMO mode against a simulated target with deterministic synthetic responses. Results illustrate the platform's evaluation, scoring and evidence workflow and must not be used as evidence about any real AI system.": "이 실행은 결정론적 합성 응답을 생성하는 시뮬레이션 대상에 대해 DEMO 모드로 수행되었습니다. 결과는 플랫폼의 평가·채점·증적 워크플로를 예시할 뿐이며 실제 AI 시스템에 대한 증거로 사용해서는 안 됩니다.",
  "Annotations were produced by rule-based checks and an LLM-as-judge (NIST AI 200-3 §6). LLM-as-judge annotations should be validated on a human-reviewed sample before the results are relied upon for conformity decisions.": "어노테이션은 규칙 기반 검사와 LLM 판정기(NIST AI 200-3 §6)로 생성되었습니다. 적합성 결정에 결과를 활용하기 전에 LLM 판정 어노테이션을 사람이 검토한 표본으로 검증해야 합니다.",
  "LLM-as-judge annotations carry model-dependent variance; multiple judge runs and human validation of a sample are recommended before relying on borderline results.": "LLM 판정 어노테이션에는 모델 의존적 편차가 있습니다. 경계선상의 결과를 신뢰하기 전에 복수의 판정 실행과 표본에 대한 사람 검증을 권고합니다.",
  // sections & labels
  "AI Assurance Score": "AI 보증 점수", "AI Assurance Score (latest run)": "AI 보증 점수(최근 실행)", "AI System Verification Report (test report)": "AI 시스템 검증 리포트(시험성적서)", "AI application(s) being evaluated": "평가 대상 AI 애플리케이션", "Acceptance criterion": "합격 기준", "Agent profile — framework:": "에이전트 프로필 — 프레임워크:", "Allowed": "허용", "Annotation items": "어노테이션 항목", "Annotation schema components": "어노테이션 스키마 구성요소", "Annotation tool: rule-based checks +": "어노테이션 도구: 규칙 기반 검사 +", "Annotation used rule-based checks plus": "어노테이션에는 규칙 기반 검사와 함께 다음을 사용했습니다:", "Annotators — sampling frame / expertise / sample size": "어노테이터 — 표본 틀 / 전문성 / 표본 크기",
  "All evaluated metrics met their acceptance thresholds. The system is recommended for approval for the evaluated scope, subject to continuous monitoring and re-test on change.": "평가된 모든 지표가 합격 임계값을 충족했습니다. 지속 모니터링과 변경 시 재시험을 조건으로, 평가 범위에 대해 승인을 권고합니다.",
  "Any change to model version, prompts, tools or data sources invalidates these results until the affected categories are re-tested (change-triggered re-evaluation).": "모델 버전·프롬프트·도구·데이터 소스가 변경되면 해당 범주를 재시험할 때까지 이 결과는 효력을 잃습니다(변경 기반 재평가).",
  "Assurance history": "보증 이력", "Authorised approver": "승인권자", "Automated red teaming complements but does not replace human red teaming; dynamic human adversaries may find failure modes not covered here.": "자동화된 레드티밍은 사람의 레드티밍을 보완할 뿐 대체하지 않습니다. 사람 공격자는 여기서 다루지 않은 실패 모드를 발견할 수 있습니다.",
  "B.1 Scope": "B.1 범위", "B.2 Design": "B.2 설계", "B.3 Materials": "B.3 자료", "B.4 Infrastructure": "B.4 인프라", "B.5 Implementation": "B.5 실행",
  "Categories": "범주", "Category": "범주", "Category score": "범주 점수", "Change events (re-test triggers)": "변경 이벤트(재시험 트리거)", "Code": "코드", "Components captured by Model Testing prompts": "모델 테스팅 프롬프트가 포착하는 구성요소", "Control": "통제", "Control implementation status": "통제 구현 상태", "Country": "국가", "Covered (controls verified + evidence)": "충족(통제 검증 + 증적)", "Current AI Assurance Score": "현재 AI 보증 점수",
  "Data & third parties": "데이터 및 제3자", "Data analysis techniques": "데이터 분석 기법", "Data collection considerations (IRB, consent, storage)": "데이터 수집 고려사항(IRB·동의·저장)", "Data schema: SessionID, Date/Time, TesterID, ApplicationID, ScenarioID, TestingType; Dialogues, Questionnaires, Annotations (implemented as TestSession / DialogueTurn / QuestionnaireResponse / Annotation).": "데이터 스키마: SessionID, Date/Time, TesterID, ApplicationID, ScenarioID, TestingType; 대화·설문·어노테이션(TestSession / DialogueTurn / QuestionnaireResponse / Annotation으로 구현).", "Dataset": "데이터셋", "Date": "날짜", "Demo mode": "데모 모드", "Demo-mode evidence included": "데모 모드 증적 포함", "Description": "설명", "Deviations, limitations and statement": "편차·제한사항 및 진술", "Dimension": "차원", "Distribution of testers": "테스터 배분",
  "EU AI Act classification": "EU AI Act 분류", "Each session is a tester–application interaction identified by SessionID with TesterID, ApplicationID, ScenarioID and TestingType; dialogues, tool calls and annotations were logged per the ARIA data schema.": "각 세션은 SessionID로 식별되는 테스터–애플리케이션 상호작용이며 TesterID, ApplicationID, ScenarioID, TestingType을 가집니다. 대화·도구 호출·어노테이션은 ARIA 데이터 스키마에 따라 기록되었습니다.", "Each test method is mapped to harmonized controls, which in turn map to framework requirements. Passing metrics mark the control as VERIFIED for this system and attach generated evidence.": "각 시험 방법은 조화 통제에 매핑되고, 조화 통제는 다시 프레임워크 요구사항에 매핑됩니다. 지표가 통과하면 해당 통제는 이 시스템에 대해 검증됨으로 표시되고 생성 증적이 첨부됩니다.", "Evaluation API:": "Evaluation API:", "Evaluation run(s)": "평가 실행", "Evaluation runs referenced": "참조된 평가 실행", "Evidence": "증적", "Evidence & reports": "증적 및 리포트", "Evidence index": "증적 색인", "Evidence type": "증적 유형", "Executed": "실행 시각", "Executive summary": "요약", "Expected evidence": "기대 증적",
  "Failed": "실패", "Findings": "발견사항", "Framework": "프레임워크", "Framework coverage": "프레임워크 커버리지", "Gaps": "갭", "Gaps and recommended actions": "갭 및 권고 조치", "Goal of Model Testing": "모델 테스팅 목표", "Goal of Red Teaming": "레드티밍 목표", "Goal of User Testing": "사용자 테스팅 목표", "Harmonized control": "조화 통제", "Harmonized controls": "조화 통제", "Human oversight": "사람의 감독", "Identity & lifecycle": "식별 및 라이프사이클", "Intended use cases": "의도된 사용 사례", "Issued": "발행일", "Judge": "판정기", "L": "L", "LLM-as-judge with human validation sample": "LLM 판정기 + 사람 검증 표본", "Last verified": "최종 검증", "Lifecycle stage": "라이프사이클 단계", "Limitations": "제한사항", "Linked controls / requirements": "연결된 통제 / 요구사항",
  "Measured": "측정값", "Method": "방법", "Methodological note": "방법론 참고", "Methodology (NIST AI 200-3 ARIA-style)": "방법론(NIST AI 200-3 ARIA 방식)", "Metric": "지표", "Metrics aggregate annotation items per test method and are compared against pre-registered acceptance thresholds.": "지표는 시험 방법별로 어노테이션 항목을 집계하고 사전 등록된 합격 임계값과 비교합니다.", "Mode": "모드", "Models": "모델", "Name": "이름", "No": "아니오", "No change events recorded.": "기록된 변경 이벤트가 없습니다.", "No findings were raised.": "발견사항이 없습니다.", "No gaps identified.": "식별된 갭이 없습니다.", "No nonconformities observed.": "부적합 사항이 관찰되지 않았습니다.", "No runs have been executed for this plan yet.": "이 계획에 대해 아직 실행된 평가가 없습니다.", "Nonconformities and observations": "부적합 및 관찰사항",
  "One or more acceptance thresholds were not met or critical findings were raised. Deployment approval should be withheld until findings are mitigated and the affected scenarios are re-run.": "하나 이상의 합격 임계값이 충족되지 않았거나 치명적 발견사항이 제기되었습니다. 발견사항이 완화되고 해당 시나리오가 재실행될 때까지 배포 승인을 보류해야 합니다.", "One or more metrics are within the warning band. Remediation is recommended before deployment approval; see findings.": "하나 이상의 지표가 경고 구간에 있습니다. 배포 승인 전 시정을 권고합니다. 발견사항을 참조하세요.", "Organization": "조직", "Overall judgement": "종합 판정", "Overview": "개요", "Owner": "책임자", "PII": "개인식별정보", "Partial": "부분", "Permissions": "권한", "Personal data": "개인정보", "Prompts / sample": "프롬프트 / 표본", "Purpose": "목적", "Questionnaire items": "설문 항목",
  "Re-test required": "재시험 필요", "Re-testing is required after any substantial modification (model version, prompt, tool, data source) per the change-impact policy.": "변경 영향 정책에 따라 중대한 변경(모델 버전·프롬프트·도구·데이터 소스) 후에는 재시험이 필요합니다.", "Red Teaming instructions": "레드티밍 지시문", "Red teamers — sampling frame / eligibility / sample size": "레드티머 — 표본 틀 / 자격 / 표본 크기", "Ref": "참조", "Reference": "참조", "Reference standard / guidance": "참조 표준 / 지침", "Report": "리포트", "Report identification": "리포트 식별", "Report type": "리포트 유형", "Reported results": "보고 결과", "Requirement": "요구사항", "Requirement coverage matrix": "요구사항 커버리지 매트릭스", "Requirements": "요구사항", "Requirements assessed": "평가된 요구사항", "Results apply to the evaluated scenarios, prompt sets and configuration only; generalisation to other contexts of use is limited (NIST AI 200-3 §7).": "결과는 평가된 시나리오·프롬프트셋·구성에만 적용되며 다른 사용 맥락으로의 일반화는 제한됩니다(NIST AI 200-3 §7).", "Results by metric": "지표별 결과", "Results summary": "결과 요약", "Risk": "위험", "Risk level": "위험 수준", "Risk register": "위험 레지스터", "Risk register extract": "위험 레지스터 발췌", "Risk score": "위험 점수", "Risk tier": "위험 등급", "Role": "역할", "Run": "실행",
  "S": "S", "Scenario": "시나리오", "Scenarios": "시나리오", "Score": "점수", "Scoring tool: metric aggregation per test method, severity weighting, category scores and AI Assurance Score": "채점 도구: 시험 방법별 지표 집계, 심각도 가중, 범주 점수 및 AI 보증 점수", "Sector": "산업", "Sensitivity": "민감도", "Service": "서비스", "Sessions": "세션", "Source": "출처", "Status": "상태", "System": "시스템", "System under evaluation": "평가 대상 시스템", "Target": "대상", "Target concept": "측정 개념", "Technical owner": "기술 책임자", "Technical reviewer": "기술 검토자", "Test conditions & environment": "시험 조건 및 환경", "Test items, methods and acceptance criteria": "시험 항목·방법 및 합격 기준", "Test method": "시험 방법", "Test mode": "시험 모드", "Test period": "시험 기간", "Test results": "시험 결과", "Tester": "시험자", "Tester / Reviewer / Approver": "시험자 / 검토자 / 승인자", "Testing platform: K-VeriAI evaluation engine — prompt delivery, dialogue collection, tester assignment, instruction display, questionnaire administration": "테스팅 플랫폼: K-VeriAI 평가 엔진 — 프롬프트 전달, 대화 수집, 테스터 배정, 지시문 표시, 설문 시행", "Testing type": "테스트 유형", "The evaluation combined": "이 평가는 다음 세션을 결합했습니다:", "This report shall not be reproduced except in full without written approval of the issuing body.": "이 리포트는 발행기관의 서면 승인 없이 전체가 아닌 일부만 복제할 수 없습니다.", "Title": "제목", "Tool": "도구", "Traceability: controls verified by this run": "추적성: 이 실행으로 검증된 통제", "Type": "유형", "User Testing instructions": "사용자 테스팅 지시문", "User testers — sampling frame / eligibility / sample size": "사용자 테스터 — 표본 틀 / 자격 / 표본 크기", "Vendor": "벤더", "Verdict": "판정", "Version": "버전", "Yes": "예", "Yes (incl. sensitive)": "예(민감정보 포함)",
  "a simulated judge over ground-truth tags": "정답 태그 기반 시뮬레이션 판정기", "adapter (Anthropic / OpenAI-compatible / HTTP Evaluation API / demo)": "어댑터(Anthropic / OpenAI 호환 / HTTP Evaluation API / 데모)", "all components": "전체 구성요소", "an LLM-as-judge with structured rationale and confidence": "구조화된 근거와 신뢰도를 제공하는 LLM 판정기", "autonomy:": "자율성:", "budget cap": "예산 한도", "built-in": "내장", "controls": "통제", "critical": "치명", "fail": "실패", "high": "높음", "kill switch:": "킬스위치:", "n": "n", "n/a": "해당 없음", "no": "아니오", "no harmonized control mapped; attach evidence directly": "매핑된 조화 통제 없음. 증적을 직접 첨부하세요", "not yet implemented": "미구현", "pass": "통과", "sessions.": "", "yes": "예",
  // renderer chrome
  "Results relate only to the items tested under the stated conditions.": "결과는 명시된 조건에서 시험된 항목에만 관련됩니다.",
  "No entries": "항목 없음", "Recommendation:": "권고:", "Signature / date": "서명 / 날짜", "Generated": "생성", "Runs:": "실행:", "This document is generated from platform records; changes to the underlying system invalidate test-derived evidence until re-evaluation.": "이 문서는 플랫폼 기록으로 생성되었습니다. 기반 시스템이 변경되면 재평가 전까지 시험 유래 증적은 효력을 잃습니다.", "Language": "언어",
};

const REPORT_DICTS: Partial<Record<Locale, Record<string, string>>> = { ko: REPORT_KO, de: REPORT_DE };

export function rt(locale: Locale, key: string): string {
  const v = REPORT_DICTS[locale]?.[key];
  return v === undefined ? key : v;
}
