import Link from "next/link";
import { Plus } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Badge, toneForStatus } from "@/components/ui/badge";
import { Table, TBody, TD, TH, THead, TR } from "@/components/ui/table";
import { Stat } from "@/components/ui/stat";
import { enumLabel, fmtDate } from "@/lib/utils";

export const metadata = { title: "Evidence Center" };

export default async function EvidencePage(props: PageProps<"/evidence">) {
  const user = await requireUser();
  const sp = await props.searchParams;
  const type = typeof sp.type === "string" ? sp.type : undefined;
  const evidence = await db.evidence.findMany({ where: { orgId: user.orgId, ...(type ? { type: type as never } : {}) }, orderBy: { createdAt: "desc" }, include: { system: true, run: true, createdBy: true, links: { include: { control: true, requirement: { include: { framework: true } } } } } });
  const all = await db.evidence.groupBy({ by: ["type"], where: { orgId: user.orgId }, _count: true });
  const counts = { generated: evidence.filter((e) => e.source === "GENERATED").length, uploaded: evidence.filter((e) => e.source === "UPLOADED").length, attestation: evidence.filter((e) => e.source === "ATTESTATION").length, expired: evidence.filter((e) => e.status === "EXPIRED").length };
  return (
    <>
      <PageHeader title="Evidence Center" description="Every artefact that proves something: test-derived evidence generated by runs, uploaded documents (policies, DPIAs, model cards) and human attestations — each an object linked to harmonized controls and reusable across ISO/IEC 42001, EU AI Act, NIST AI RMF and KR AI Basic Act packs." actions={<Link href="/evidence/new"><Button><Plus className="h-4 w-4" /> Add evidence</Button></Link>} />
      <div className="mb-4 grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Generated (test-derived)" value={counts.generated} /><Stat label="Uploaded documents" value={counts.uploaded} /><Stat label="Attestations" value={counts.attestation} /><Stat label="Expired (re-test needed)" value={counts.expired} tone={counts.expired ? "warning" : undefined} /></div>
      <div className="mb-3 flex flex-wrap gap-1"><Link href="/evidence"><Badge tone={!type ? "primary" : "neutral"} className="cursor-pointer">All</Badge></Link>{all.map((g) => <Link key={g.type} href={`/evidence?type=${g.type}`}><Badge tone={type === g.type ? "primary" : "neutral"} className="cursor-pointer">{enumLabel(g.type)} ({g._count})</Badge></Link>)}</div>
      <div className="rounded-lg border border-border bg-surface"><Table><THead><TR><TH>Type</TH><TH>Title</TH><TH>System</TH><TH>Source</TH><TH>Linked controls / requirements</TH><TH>Status</TH><TH>Valid from</TH><TH>By</TH></TR></THead><TBody>
        {evidence.map((e) => <TR key={e.id}><TD><Badge>{enumLabel(e.type)}</Badge></TD><TD><Link href={`/evidence/${e.id}`} className="font-medium hover:underline">{e.title}</Link>{e.description && <div className="line-clamp-1 text-xs text-muted">{e.description}</div>}{e.run && <div className="text-[11px] text-muted">from run {e.run.code}</div>}</TD><TD className="text-xs">{e.system?.code ?? <span className="text-muted">org-level</span>}</TD><TD><Badge tone={e.source === "GENERATED" ? "primary" : e.source === "ATTESTATION" ? "accent" : "neutral"}>{enumLabel(e.source)}</Badge></TD><TD className="text-xs">{[...new Set(e.links.map((l) => l.control?.code ?? (l.requirement ? `${enumLabel(l.requirement.framework.code)} ${l.requirement.ref}` : null)).filter(Boolean))].join(", ") || "—"}</TD><TD><Badge tone={toneForStatus(e.status)}>{enumLabel(e.status)}</Badge></TD><TD className="text-xs text-muted">{fmtDate(e.validFrom)}</TD><TD className="text-xs">{e.createdBy?.name ?? "system"}</TD></TR>)}
      </TBody></Table></div>
    </>
  );
}
